[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'


[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'ujihisa/neco-look'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
	"w0rp/aleの設定
	let g:ale_sign_error = 'X'
	let g:ale_sign_warning = '!'
	let g:ale_linters = {
	\	 'javascript': ['eslint'],
	\	 'python': ['pylint'],
	\	 'c': ['gcc'],
	\	 'cpp': ['gcc'],
	\	 'Java': ['javac'],
	\}
	" Only run linters named in ale_linters settings.
	let g:ale_linters_explicit = 1
	"常にale表示
	let g:ale_sign_column_always = 1
'''
